datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
  # - name: Tempo
  #   type: tempo
  #   access: proxy
  #   url: http://tempo:3200
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: false
  #   apiVersion: 1
  #   uid: tempo
  #   jsonData:
  #     httpMethod: GET
  #     serviceMap:
  #       datasourceUid: prometheus
  #     streamingEnabled:
  #       search: true