global:
  scrape_interval: 5s #Scrape interval to every 15 seconds.
  evaluation_interval: 5s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nanoservice-http"
    static_configs:
      - targets: ["nanoservice-http:4000"]

  # - job_name: 'nanoservice-http'
  #   static_configs:
  #     - targets: ['telegraf:9273']